version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.20.0
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: "server -dev"


  source-management-mongo-db:
    image: mongo:6
    container_name: source-management-mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./local-mongo-init:/docker-entrypoint-initdb.d:ro

  source-management-postgres:
    image: postgres:15
    container_name: source-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source-management
    ports:
      - "5432:5432"
    volumes:
      - source_management_postgres_data:/var/lib/postgresql/data

  admin-panel-postgres:
    image: postgres:15
    container_name: admin-panel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_panel
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - admin_panel_postgres_data:/var/lib/postgresql/data

  source-management:
    build:
      context: ./source_management
      dockerfile: Dockerfile
    container_name: source-management
    ports:
      - "8000:8000"
    environment:
      CONTAINER_TYPE: fastapi
      ENVIRONMENT: dev
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@source-management-postgres:5432/source-management
      MONGO_URI: mongodb://source-management-mongo-db:27017
      VAULT_ADDR: http://vault:8200
    depends_on:
      - source-management-postgres
      - source-management-migrator
      - source-management-mongo-db
    restart: unless-stopped

  conversation:
    build:
      context: ./conversation
      dockerfile: Dockerfile
    container_name: conversation
    ports:
      - "8001:8000"
    environment:
      CONTAINER_TYPE: fastapi
      ENVIRONMENT: dev
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@admin-panel-postgres:5433/admin_panel
    restart: unless-stopped

  admin-panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    container_name: admin-panel
    ports:
      - "8002:8000"
    environment:
      CONTAINER_TYPE: fastapi
      ENVIRONMENT: dev
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@admin-panel-postgres:5433/admin_panel
    depends_on:
      - admin-panel-postgres
      - admin-panel-migrator
    restart: unless-stopped

  source-management-migrator:
    build:
      context: ./source_management
      dockerfile: Dockerfile
    container_name: source-management-migrator
    depends_on:
      - source-management-postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@source-management-postgres:5432/source_management
    entrypoint: >
      bash -c "alembic upgrade head"
    restart: "no"

  admin-panel-migrator:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    container_name: admin-panel-migrator
    depends_on:
      - admin-panel-postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@admin-panel-postgres:5433/admin_panel
    entrypoint: >
      bash -c "alembic upgrade head"
    restart: "no"


volumes:
  source_management_postgres_data:
  admin_panel_postgres_data:
  mongo_data:
