version = 0.1
[dev.deploy.parameters]
stack_name = "ai-custom-bot-infr-dev"
resolve_s3 = true
s3_prefix = "ai-custom-bot-infr-dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []

[prod.deploy.parameters]
stack_name = "ai-custom-bot-infr-prod"
resolve_s3 = true
s3_prefix = "ai-custom-bot-infr-prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []