AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "AdminPanelApiGateway-dev"
      StageName: "test"
      TracingEnabled: true
      BinaryMediaTypes:
        - "multipart/form-data"
        - "application/json"

  CreatePromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.create_prompt
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        CreatePromptApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/prompts
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3

  CreateAgentChatBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.create_agent_chat_bot
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        CreateAgentChatBotApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/agent_chat_bots
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3

  ChangeSettingsAgentChatBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.change_settings_agent_chat_bot
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        ChangeSettingsAgentChatBotApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/agent_chat_bots
            Method: PUT
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3
