AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: 'Environment (dev or prod)'
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

  VpcStackName:
    Description: 'Name of the VPC stack to import resources from'
    Type: String
    Default: ai-custom-bot-infr

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "AdminPanelApiGateway-${Environment}"
      StageName: "test"
      TracingEnabled: true
      BinaryMediaTypes:
        - "multipart/form-data"
        - "application/json"

  CreatePromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreatePrompt-${Environment}"
      Handler: src.entrypoints.api.handlers.create_prompt
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        CreatePromptApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/prompts
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"

  CreateAgentChatBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreateAgentChatBot-${Environment}"
      Handler: src.entrypoints.api.handlers.create_agent_chat_bot
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        CreateAgentChatBotApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/agent_chat_bots
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"

  ChangeSettingsAgentChatBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ChangeSettingsAgentChatBot-${Environment}"
      Handler: src.entrypoints.api.handlers.change_settings_agent_chat_bot
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        ChangeSettingsAgentChatBotApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/agent_chat_bots
            Method: PUT
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"

  UpdatePromptTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "UpdatePromptText-${Environment}"
      Handler: src.entrypoints.api.handlers.update_prompt_text
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        UpdatePromptTextApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/prompts
            Method: PUT
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"
