"""empty message

Revision ID: 0837631aad93
Revises: 7f1da8745a9b
Create Date: 2025-01-02 01:58:25.740242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0837631aad93"
down_revision: Union[str, None] = "7f1da8745a9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resources", sa.Column("extension", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "extension")
    # ### end Alembic commands ###
