"""empty message

Revision ID: 275e23c7dca6
Revises: c865c080a351
Create Date: 2025-01-29 21:31:39.267786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "275e23c7dca6"
down_revision: Union[str, None] = "c865c080a351"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources", sa.Column("dynamodb_table_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "dynamodb_table_name")
    # ### end Alembic commands ###
