"""empty message

Revision ID: 7f1da8745a9b
Revises: 2e348411b5d9
Create Date: 2024-12-17 01:18:10.632176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f1da8745a9b"
down_revision: Union[str, None] = "2e348411b5d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge_bases", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge_bases", "name")
    # ### end Alembic commands ###
