"""empty message

Revision ID: 845774b2151c
Revises: 275e23c7dca6
Create Date: 2025-09-19 06:18:25.536272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845774b2151c'
down_revision: Union[str, None] = '275e23c7dca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'user_id')
    # ### end Alembic commands ###
