"""empty message

Revision ID: c865c080a351
Revises: 0837631aad93
Create Date: 2025-01-17 01:32:16.498780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c865c080a351"
down_revision: Union[str, None] = "0837631aad93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources", sa.Column("google_drive_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "google_drive_url")
    # ### end Alembic commands ###
