
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation
  namespace: ai-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversation
  template:
    metadata:
      labels:
        app: conversation
    spec:
      containers:
      - name: conversation
        image: ai-assistant/conversation:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-config
              key: conversation-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-config
              key: openai-key
---
apiVersion: v1
kind: Service
metadata:
  name: conversation-service
  namespace: ai-assistant
spec:
  selector:
    app: conversation
  ports:
  - port: 8000
    targetPort: 8000
