
apiVersion: v1
kind: Secret
metadata:
  name: firebase-config
  namespace: ai-assistant
type: Opaque
data:
  project-id: <base64-encoded-project-id>
  private-key: <base64-encoded-private-key>
  client-email: <base64-encoded-client-email>
---
apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: ai-assistant
type: Opaque
data:
  admin-panel-url: <base64-encoded-db-url>
  source-management-url: <base64-encoded-db-url>
  conversation-url: <base64-encoded-db-url>
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-config
  namespace: ai-assistant
type: Opaque
data:
  openai-key: <base64-encoded-openai-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-config
  namespace: ai-assistant
type: Opaque
data:
  host: <base64-encoded-opensearch-host>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
