
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: ai-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ui-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ui-files
        configMap:
          name: ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: ai-assistant
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: ai-assistant
data:
  index.html: |
    # UI content would be placed here
