AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: 'Environment (dev or prod)'
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

  VpcStackName:
    Description: 'Name of the VPC stack to import resources from'
    Type: String
    Default: ai-custom-bot-infr

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "SourceManagementApiGateway-${Environment}"
      StageName: !Ref Environment
      TracingEnabled: true
      BinaryMediaTypes:
        - "multipart/form-data"
        - "application/json"

  MSSQLLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mssql-layer
      Description: Layer with MSSQL dependencies
      ContentUri: ./lambda-mssql-layer/lambda-mssql-layer.zip
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  CreateResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreateResource-${Environment}"
      Handler: src.entrypoints.api.handlers.create_resource
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        CreateResourceApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/resources
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"

  GetResourceIdsByKnowledgeBaseIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetResourceIdsByKnowledgeBaseId-${Environment}"
      Handler: src.entrypoints.api.handlers.get_resource_ids_by_knowledge_base_id
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        GetResourceIdsByKnowledgeBaseIdApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/resources
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"
      AutoPublishAlias: !Ref Environment
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 5

  GetAllResourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "GetAllResources-${Environment}"
      Handler: src.entrypoints.api.handlers.get_all_resources
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        GetAllResourcesApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/resources/all
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"

  CreateKnowledgeBaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "CreateKnowledgeBase-${Environment}"
      Handler: src.entrypoints.api.handlers.create_knowledge_base
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: !Sub "${Environment}"
          REGION: !Sub "${AWS::Region}"
      Tracing: Active
      Events:
        CreateKnowledgeBaseApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/knowledge_bases
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-LambdaSGId"
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetA"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetB"
          - Fn::ImportValue:
              !Sub "${VpcStackName}-PrivateSubnetC"
