AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "SourceManagementApiGateway-dev"
      StageName: "test"
      TracingEnabled: true
      BinaryMediaTypes:
        - "multipart/form-data"
        - "application/json"

  MSSQLLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mssql-layer
      Description: Layer with MSSQL dependencies
      ContentUri: ./lambda-mssql-layer/lambda-mssql-layer.zip
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  CreateResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.create_resource
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        CreateResourceApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/resources
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3

  GetResourceIdsByKnowledgeBaseIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.get_resource_ids_by_knowledge_base_id
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        GetResourceIdsByKnowledgeBaseIdApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/resources
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3

  GetAllResourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.get_all_resources
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        GetAllResourcesApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/resources/all
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3

  CreateKnowledgeBaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.entrypoints.api.handlers.create_knowledge_base
      Runtime: python3.12
      CodeUri: .
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - SecretsManagerReadWrite
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref MSSQLLayer
      Environment:
        Variables:
          AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
      Tracing: Active
      Events:
        CreateKnowledgeBaseApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /api/v1/knowledge_bases
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0159afa3ca6ce8d06
        SubnetIds:
          - subnet-01a6f0d8ab5654d8e
          - subnet-0870c5719ed26e6c1
          - subnet-0544758b0bdeb9cf3
